# Generated by Django 4.2.30 on 2026-06-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('ak', 'Twi'), ('ee', 'Ewe'), ('ha', 'Hausa'), ('gaa', 'Ga'), ('dag', 'Dagbani'), ('fat', 'Fante')], default='en', max_length=10),
        ),
    ]
