# Generated by Django 6.0.6 on 2026-06-13 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_introduced', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('video_duration_seconds', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['week', 'day_introduced', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('programming', 'Programming'), ('aws', 'AWS & Cloud'), ('system_design', 'System Design & Architecture'), ('ml_ai', 'ML & AI'), ('blockchain', 'Blockchain'), ('ai_agents', 'AI Agents'), ('devops', 'DevOps'), ('security', 'Security')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_for_week', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('code_scratch', 'Code from scratch'), ('debug', 'Debug this'), ('extend', 'Extend this'), ('explain', 'Explain your code'), ('design', 'Design this'), ('review', 'Review this'), ('mcq', 'Multiple choice'), ('spot_bug', 'Spot the bug'), ('refactor', 'Refactor this'), ('edge_case', 'Security / edge case')], max_length=20)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('content', models.JSONField()),
                ('answer_rubric', models.JSONField()),
                ('socratic_clue', models.TextField(blank=True)),
                ('scaffolded_hint', models.TextField(blank=True)),
                ('micro_explanation', models.TextField(blank=True)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='curriculum.concept')),
            ],
            options={
                'ordering': ['concept', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tests', to='curriculum.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='curriculum.subjectarea')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('outcome', models.CharField(blank=True, choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('partial', 'Partial')], max_length=20)),
                ('ai_feedback', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('clue_used', models.BooleanField(default=False)),
                ('hint_used', models.BooleanField(default=False)),
                ('explanation_used', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='curriculum.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='curriculum.course')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('course', 'number')},
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='curriculum.week'),
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('mastered', 'Mastered'), ('weak', 'Weak — needs revisit')], default='not_started', max_length=20)),
                ('consecutive_correct_hard', models.PositiveIntegerField(default=0)),
                ('highest_difficulty_passed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('best_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('first_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='curriculum.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Concept masteries',
                'ordering': ['concept'],
                'unique_together': {('user', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('code_submission', models.TextField(blank=True)),
                ('readme', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('evaluating', 'Evaluating'), ('passed', 'Passed'), ('revision_needed', 'Revision needed'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('ai_score', models.JSONField(blank=True, null=True)),
                ('ai_feedback_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='curriculum.week')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'week')},
            },
        ),
        migrations.CreateModel(
            name='DayProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('in_progress', 'In progress'), ('passed', 'Passed')], default='locked', max_length=20)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('passed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_progresses', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_progresses', to='curriculum.week')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('user', 'week', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='BuildLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('entry', models.TextField()),
                ('ai_prompt_used', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_logs', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_logs', to='curriculum.week')),
            ],
            options={
                'ordering': ['week', 'day_number'],
                'unique_together': {('user', 'week', 'day_number')},
            },
        ),
    ]
