# Generated by Django 4.2.30 on 2026-06-22 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_script', models.TextField()),
                ('audio_file', models.FileField(blank=True, upload_to='concept_audio/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='curriculum.concept')),
            ],
        ),
    ]
