# Generated by Django 4.2.30 on 2026-06-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_conceptlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ak', 'Twi'), ('ee', 'Ewe'), ('ha', 'Hausa'), ('gaa', 'Ga'), ('dag', 'Dagbani'), ('fat', 'Fante')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
