# Generated by Django 6.0.6 on 2026-06-24 21:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_course_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptmastery',
            name='lesson_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DayProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('starter_code', models.TextField(blank=True)),
                ('answer_rubric', models.JSONField(default=dict)),
                ('is_cumulative', models.BooleanField(default=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_problems', to='curriculum.week')),
            ],
            options={
                'ordering': ['week', 'day_number'],
                'unique_together': {('week', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='DayProblemSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True)),
                ('code_submission', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('evaluating', 'Evaluating'), ('passed', 'Passed'), ('revision_needed', 'Revision needed')], default='evaluating', max_length=20)),
                ('ai_score', models.JSONField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='curriculum.dayproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_problem_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['problem'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(choices=[(1, 'Set A'), (2, 'Set B')])),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('scheduled', 'Scheduled'), ('available', 'Available'), ('passed', 'Passed'), ('failed', 'Failed')], default='available', max_length=20)),
                ('question_ids', models.JSONField(default=list)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='curriculum.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['concept', 'set_number'],
                'unique_together': {('user', 'concept', 'set_number')},
            },
        ),
    ]
